version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/source/"
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/source/BugzillaLyoArchives"
    open-pull-requests-limit: 30
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 30
    schedule:
      interval: "daily"